# Generated by Django 2.2.16 on 2020-09-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_jhgjhgjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhgjhg',
        ),
    ]
