# Generated by Django 2.2.16 on 2020-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_jhgjhgjhg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HGFHjf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgjhgfhjg', models.BigIntegerField()),
            ],
        ),
    ]
